FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/firmware-sim ./cmd/firmware-sim

FROM alpine:3.21
RUN apk upgrade --no-cache && apk --no-cache add ca-certificates
COPY --from=builder /bin/firmware-sim /bin/firmware-sim
ENTRYPOINT ["/bin/firmware-sim"]
