// Code generated by protoc-gen-go. DO NOT EDIT.
// Package api provides Go types mirroring the protobuf definitions in proto/device/device.proto.
// In production, run: protoc --go_out=. --go-grpc_out=. proto/device/device.proto

package api

import (
	"context"
	"io"
)

// DeviceType enum
type DeviceType int32

const (
	DeviceTypeUnspecified DeviceType = 0
	DeviceTypeCamera      DeviceType = 1
	DeviceTypeAccessControl DeviceType = 2
	DeviceTypeAlarm       DeviceType = 3
	DeviceTypeSensor      DeviceType = 4

	// Proto-style aliases for compatibility
	DeviceType_DEVICE_TYPE_UNSPECIFIED = DeviceTypeUnspecified
	DeviceType_CAMERA                  = DeviceTypeCamera
	DeviceType_ACCESS_CONTROL          = DeviceTypeAccessControl
	DeviceType_ALARM                   = DeviceTypeAlarm
	DeviceType_SENSOR                  = DeviceTypeSensor
)

// DeviceStatus enum
type DeviceStatus int32

const (
	DeviceStatusUnspecified  DeviceStatus = 0
	DeviceStatusOnline       DeviceStatus = 1
	DeviceStatusOffline      DeviceStatus = 2
	DeviceStatusMaintenance  DeviceStatus = 3
	DeviceStatusDecommissioned DeviceStatus = 4

	// Proto-style aliases
	DeviceStatus_DEVICE_STATUS_UNSPECIFIED = DeviceStatusUnspecified
	DeviceStatus_ONLINE                    = DeviceStatusOnline
	DeviceStatus_OFFLINE                   = DeviceStatusOffline
	DeviceStatus_MAINTENANCE               = DeviceStatusMaintenance
	DeviceStatus_DECOMMISSIONED            = DeviceStatusDecommissioned
)

// Severity enum
type Severity int32

const (
	SeverityUnspecified Severity = 0
	SeverityInfo        Severity = 1
	SeverityWarning     Severity = 2
	SeverityCritical    Severity = 3
)

// FirmwareDeploymentStatus enum
type FirmwareDeploymentStatus int32

const (
	FirmwareDeploymentStatusUnspecified FirmwareDeploymentStatus = 0
	FirmwareDeploymentStatusPending     FirmwareDeploymentStatus = 1
	FirmwareDeploymentStatusDownloading FirmwareDeploymentStatus = 2
	FirmwareDeploymentStatusVerifying   FirmwareDeploymentStatus = 3
	FirmwareDeploymentStatusApplying    FirmwareDeploymentStatus = 4
	FirmwareDeploymentStatusCompleted   FirmwareDeploymentStatus = 5
	FirmwareDeploymentStatusFailed      FirmwareDeploymentStatus = 6
	FirmwareDeploymentStatusRolledBack  FirmwareDeploymentStatus = 7
)

// Protobuf message types (simplified for development)
type Device struct {
	DeviceId        string
	SerialNumber    string
	DeviceType      DeviceType
	Model           string
	FirmwareVersion string
	Status          DeviceStatus
	SiteId          string
	OrganizationId  string
	IpAddress       string
	MacAddress      string
	LastHeartbeat   int64
	Config          map[string]string
	CreatedAt       int64
	UpdatedAt       int64
}

type DeviceHealth struct {
	DeviceId         string
	CpuUsage         float64
	MemoryUsage      float64
	TemperatureC     float64
	UptimeSeconds    int64
	NetworkLatencyMs float64
	LastReported     int64
}

type Event struct {
	EventId   string
	DeviceId  string
	EventType string
	Severity  Severity
	Payload   map[string]string
	Timestamp int64
}

type Firmware struct {
	Version        string
	DeviceType     DeviceType
	BinaryUrl      string
	ChecksumSha256 string
	ReleaseNotes   string
	CreatedAt      int64
}

type RegisterRequest struct {
	SerialNumber   string
	DeviceType     DeviceType
	Model          string
	SiteId         string
	OrganizationId string
	IpAddress      string
	MacAddress     string
	Config         map[string]string
}

type RegisterResponse struct {
	Device *Device
}

type HeartbeatRequest struct {
	DeviceId string
	Health   *DeviceHealth
}

type HeartbeatResponse struct {
	ConfigUpdated          bool
	Config                 map[string]string
	PendingFirmwareVersion string
}

type EventRequest struct {
	Event *Event
}

type EventResponse struct {
	EventId      string
	Acknowledged bool
}

type FirmwareRequest struct {
	DeviceId   string
	Version    string
	DeviceType DeviceType
}

type FirmwareChunk struct {
	Version        string
	ChunkIndex     int32
	TotalChunks    int32
	Data           []byte
	ChecksumSha256 string
}

type FirmwareStatusRequest struct {
	DeviceId     string
	Version      string
	Status       FirmwareDeploymentStatus
	ErrorMessage string
}

type FirmwareStatusResponse struct {
	Acknowledged bool
}

type ConfigRequest struct {
	DeviceId string
}

type ConfigResponse struct {
	Config          map[string]string
	FirmwareVersion string
}

// DeviceService_StreamFirmwareServer is the server stream for StreamFirmware.
type DeviceService_StreamFirmwareServer interface {
	Send(*FirmwareChunk) error
	Context() context.Context
}

// DeviceServiceServer is the gRPC service interface.
type DeviceServiceServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	SendHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	SendEvent(context.Context, *EventRequest) (*EventResponse, error)
	StreamFirmware(*FirmwareRequest, DeviceService_StreamFirmwareServer) error
	ReportFirmwareStatus(context.Context, *FirmwareStatusRequest) (*FirmwareStatusResponse, error)
	GetConfig(context.Context, *ConfigRequest) (*ConfigResponse, error)
}

// UnimplementedDeviceServiceServer provides default implementations.
type UnimplementedDeviceServiceServer struct{}

func (UnimplementedDeviceServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, nil
}
func (UnimplementedDeviceServiceServer) SendHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, nil
}
func (UnimplementedDeviceServiceServer) SendEvent(context.Context, *EventRequest) (*EventResponse, error) {
	return nil, nil
}
func (UnimplementedDeviceServiceServer) StreamFirmware(*FirmwareRequest, DeviceService_StreamFirmwareServer) error {
	return nil
}
func (UnimplementedDeviceServiceServer) ReportFirmwareStatus(context.Context, *FirmwareStatusRequest) (*FirmwareStatusResponse, error) {
	return nil, nil
}
func (UnimplementedDeviceServiceServer) GetConfig(context.Context, *ConfigRequest) (*ConfigResponse, error) {
	return nil, nil
}

// Ensure io is referenced (used in streaming handlers)
var _ = io.EOF

// RegisterDeviceServiceServer registers a DeviceServiceServer implementation.
func RegisterDeviceServiceServer(srv interface{}, impl DeviceServiceServer) {
	// In production, this would be generated by protoc-gen-go-grpc.
	// This stub allows manual registration with a standard grpc.Server.
}

